In [1]:
import tensorflow as tf
import os
import keras
import numpy as np
from keras.preprocessing import image
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics
from sklearn.metrics import ConfusionMatrixDisplay
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interactive
import csv
import pickle
import cv2
%matplotlib inline

In [2]:
unsup_model = pickle.load(open("km1.pkl", "rb"))

In [3]:
import numpy as np
from keras.preprocessing import image

path = 'C:/Users/Dikshant Gupta/Desktop/Micro Silkworm Prj/JPEGImages_xray_Kmean/Test/'

# print(img)
# plt.imshow(img)
# plt.show()

for file in os.listdir(path):
    img=cv2.imread(path+file)
    img=cv2.resize(img,(200,200))
    img=img.astype('float32')

    img_data = np.array(img)
    img_data = img_data/255.0
    img_reshape = img_data.reshape(len(img_data),-1)
    print(img_reshape)

    # result = unsup_model.predict(img_reshape)
    # print(result)
    break

[[0.1254902  0.1254902  0.1254902  ... 0.09019608 0.09019608 0.09019608]
 [0.11372549 0.11372549 0.11372549 ... 0.09411765 0.09411765 0.09411765]
 [0.08627451 0.08627451 0.08627451 ... 0.10588235 0.10588235 0.10588235]
 ...
 [0.12156863 0.12156863 0.12156863 ... 0.11764706 0.11764706 0.11764706]
 [0.08627451 0.08627451 0.08627451 ... 0.11372549 0.11372549 0.11372549]
 [0.06666667 0.06666667 0.06666667 ... 0.10588235 0.10588235 0.10588235]]


In [19]:
# from sklearn.cluster import KMeans
# from sklearn import metrics
# import numpy as np
# import matplotlib.pyplot as plt

# x1 = np.array([3, 1, 1, 2, 1, 6, 6, 6, 5, 6, 7, 8, 9, 8, 9, 9, 8])
# x2 = np.array([5, 4, 6, 6, 5, 8, 6, 7, 6, 7, 1, 2, 1, 2, 3, 2, 3])

# # create new plot and data
# plt.plot()
# X = np.array(list(zip(x1, x2))).reshape(len(x1), 2)
# colors = ['b', 'g', 'c']
# markers = ['o', 'v', 's']

# # KMeans algorithm 
# K = 3
# kmeans_model = KMeans(n_clusters=K).fit(X)

# print(kmeans_model.cluster_centers_)
# centers = np.array(kmeans_model.cluster_centers_)

# plt.plot()
# plt.title('k means centroids')

# for i, l in enumerate(kmeans_model.labels_):
#     plt.plot(x1[i], x2[i], color=colors[l], marker=markers[l],ls='None')
#     plt.xlim([0, 10])
#     plt.ylim([0, 10])

# plt.scatter(centers[:,0], centers[:,1], marker="x", color='r')
# plt.show()